owner: kidow 
repo: status

sites:
  - name: admin.
    url: https://admin.kidow.me
  - name: archive.
    url: https://archive.kidow.me
  - name: blog.
    url: https://blog.kidow.me
  - name: components.
    url: https://components.kidow.me
  - name: log.
    url: https://log.kidow.me
  - name: opengraph.
    url: https://opengraph.kidow.me
  - name: portal.
    url: https://portal.kidow.me
  - name: resume.
    url: https://resume.kidow.me
  - name: www.
    url: https://www.kidow.me

status-website:
  cname: status.kidow.me
  logoUrl: https://raw.githubusercontent.com/kidow/status/875a552b5b4d21cffa8ad059b75891d747abf452/assets/logo.svg
  name: kidow's status of projects
